In [1]:
import pandas as pd
import numpy as np

In [2]:
path = '../entrega2/airflow/data/predicciones_2025_01_12.parquet' 
df = pd.read_parquet(path)
df.head()

   customer_id  product_id purchase_date  prediction  probability
0        25734         124    2025-01-12           0     0.072984
1        25734        1304    2025-01-12           0     0.164897
2        25734        1370    2025-01-12           0     0.163196
3        25734        1372    2025-01-12           0     0.115643
4        25734       10652    2025-01-12           0     0.082400

In [3]:
df.drop(columns=['purchase_date', 'probability'], inplace=True)

In [5]:
df = df[df['prediction'] == 1]

In [6]:
df

        customer_id  product_id  prediction
114           25749         124           1
115           25749        1304           1
116           25749        1370           1
118           25749       10652           1
119           25749       11262           1
...             ...         ...         ...
169855       251391       44914           1
169856       251391       52620           1
169857       251391       48694           1
169858       251391        1206           1
169859       251391       10790           1

[5353 rows x 3 columns]

In [7]:
df.drop(columns=['prediction'], inplace=True)

C:\Users\crist\AppData\Local\Temp\ipykernel_55756\3534484310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['prediction'], inplace=True)

In [11]:
#pasar ids a entero
df['customer_id'] = df['customer_id'].astype(np.int64)
df['product_id'] = df['product_id'].astype(np.int64)

C:\Users\crist\AppData\Local\Temp\ipykernel_55756\2007627464.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_id'] = df['customer_id'].astype(np.int64)
C:\Users\crist\AppData\Local\Temp\ipykernel_55756\2007627464.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['product_id'] = df['product_id'].astype(np.int64)

In [12]:
#df a csv sin header
df.to_csv('predicciones_clientes_2025_01_01.csv', index=False, header=False)

In [ ]:
dex=False, header=True)